### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Nabav** [scheiblingco/code-cmd-repeat#2]
I get the following error:

`command 'extension.saveAndRepeatLastCommand' not found`

Extension: v0.1.0
VSCode: 1.71.2
OS: Linux

Let me know, how I can provide more debug info.

**Comment by scheibling** [comment]
@Nabav Let me look into this, looks like the command isn't registering for some reason... 
What flavour of Linux* are you running?

**Comment by Nabav** [comment]
Debian 11

**Comment by scheibling** [comment]
Found the issue, made a typo on that command in package.json. New version coming up in a few minutes!

**Comment by scheibling** [comment]
Resolved through a4afef8b7a6f8cfd53432ac19d204855e0ac12de, version 0.1.2 is now up on VS Marketplace (And OpenVSX as soon as they get their service back online)

Feel free to re-open if the problem persists!

**Comment by Nabav** [comment]
Thanks. It works now.
